// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(WebApplication1Context))]
    [Migration("20240305005251_Create_Added_Header")]
    partial class Create_Added_Header
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("WebApplication1.Data.CodingRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenomeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Header")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Location")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sequence")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GenomeId");

                    b.ToTable("CodingRegions");
                });

            modelBuilder.Entity("WebApplication1.Data.Genome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genomes");
                });

            modelBuilder.Entity("WebApplication1.Data.CodingRegion", b =>
                {
                    b.HasOne("WebApplication1.Data.Genome", null)
                        .WithMany("Proteins")
                        .HasForeignKey("GenomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Data.Genome", b =>
                {
                    b.Navigation("Proteins");
                });
#pragma warning restore 612, 618
        }
    }
}
